name: CD

on:
  pull_request:
    branches: [deploy]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.aws_access_key_id }}
          secret_key: ${{ secrets.aws_secret_access_key }}
          registry: ${{ secrets.registry }}
          repo: git-action-template
          region: ap-southeast-1
          dockerfile: service/Dockerfile

# Additional job to handle the deployment or other steps can be added